<!-- application/views/scripts/guestbook/index.phtml -->
<section class="main">
    <nav class="inner-nav"><a href="<?php
echo $this->url(
        array(
    'controller' => 'guestbook',
    'action' => 'sign'
        ), 'default', true)
?>">Sign Our Guestbook</a></nav>

    
    <section id="guestbook-entries">
        <h1>Guestbook Entries</h1>
        <?php
        if (!empty($this->entries)):
            foreach ($this->entries as $entry):
                ?>
                <article>
                    <div><?php echo $this->escape($entry->email) ?></div>
                    <p><?php echo $this->escape($entry->comment) ?></p>
                </article>
                <?php
            endforeach;
        else:
            ?>
            No entries found.
        <?php
        endif;
        ?>
    </section>
</section>