<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="x-ua-compatible" content="IE=100" />
        <meta charset="utf-8">
        <title>Zend Framework Quick Start Application</title>
        <?php 
        $baseUrl = $this->baseUrl(); 
        if (!empty($baseUrl)): echo '<base href="'.$baseUrl.'">'; endif;
        echo $this->headLink()->appendStylesheet($this->baseUrl('css/global.css')) . "\n"; 
        ?>         
        <!--[if lt IE 9]>        
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div id="header-inner">
                <hgroup id="header-logo">
                    <h1>ZF Quick Start Application</h1>
                    <h2>Modified by Paul Albinson</h2>
                </hgroup>
                <nav id="header-navigation">
                    <a href="<?php echo $this->baseUrl(); ?>" title="Back to home">Home</a> 
                    <a href="<?php
        echo $this->url(
                array('controller' => 'guestbook'), 'default', true)
        ?>">Guestbook</a>
                </nav>
            </div>
        </header>       
        <?php echo $this->layout()->content ?>
    </body>
</html>